# Generated by Django 3.2 on 2021-06-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeofproduct',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('OLD', 'OLD')], default='OLD', max_length=3),
        ),
    ]
