# Generated by Django 3.2 on 2021-06-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analiz', '0003_alter_typeofproduct_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeofproduct',
            name='status',
            field=models.CharField(blank=True, choices=[('25-51', '25-51'), ('50-101', '50-101'), ('20-51', '20-51'), ('25-51', '25-101')], max_length=10, null=True),
        ),
    ]
