# Generated by Django 3.1.7 on 2021-06-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analiz', '0004_auto_20210616_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='link_to_seo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sel_acc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
