# Generated by Django 3.2 on 2021-06-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analiz', '0004_alter_typeofproduct_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeofproduct',
            name='status',
        ),
        migrations.AddField(
            model_name='typeofproduct',
            name='status_min',
            field=models.IntegerField(blank=True, default=25, null=True),
        ),
        migrations.AddField(
            model_name='typeofproduct',
            name='status_need',
            field=models.IntegerField(blank=True, default=101, null=True),
        ),
    ]
