# Generated by Django 3.1.7 on 2021-06-18 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analiz', '0005_auto_20210618_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='changes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
