# Generated by Django 3.2 on 2021-07-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analiz', '0008_typeofproduct_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeofproduct',
            name='status',
            field=models.CharField(choices=[('InDev', 'В разработке'), ('IsS', 'Продается'), ('AN_ISS', 'Другая причина'), ('BAN', 'Бан'), ('OOS', 'Нет на складе'), ('SSS', 'Ограничение')], default='IsS', max_length=20),
        ),
    ]
