# Generated by Django 3.2 on 2021-07-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analiz', '0010_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='chat_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
