# Generated by Django 3.2 on 2021-07-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analiz', '0012_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='chat_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
