# Generated by Django 3.2 on 2021-07-13 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analiz', '0013_alter_message_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat_id',
        ),
    ]
