# Generated by Django 3.2 on 2021-07-20 08:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analiz', '0015_auto_20210720_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='acos',
            name='date',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
