# Generated by Django 3.2 on 2021-07-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analiz', '0016_acos_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acos',
            name='date',
            field=models.CharField(max_length=50),
        ),
    ]
