# Generated by Django 3.2 on 2021-07-20 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analiz', '0017_alter_acos_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acos',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analiz.typeofproduct'),
        ),
    ]
