# Generated by Django 3.2 on 2021-07-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analiz', '0018_alter_acos_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acos',
            name='acos',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='acos',
            name='budget',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
