# Generated by Django 3.2 on 2021-07-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analiz', '0019_auto_20210721_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeofproduct',
            name='adver',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=3),
        ),
        migrations.AlterField(
            model_name='acos',
            name='acos',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
    ]
