# Generated by Django 3.2 on 2021-09-13 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analiz', '0019_product_fba_inventory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manager',
            options={'ordering': ['username']},
        ),
    ]
