# Generated by Django 3.2 on 2021-09-13 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analiz', '0020_alter_manager_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['brand']},
        ),
    ]
