# Generated by Django 3.2 on 2021-07-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analiz', '0020_auto_20210721_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acos',
            name='acos',
            field=models.IntegerField(),
        ),
    ]
