# Generated by Django 3.2 on 2021-09-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analiz', '0022_auto_20210913_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeofproduct',
            name='status_min',
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='typeofproduct',
            name='status_need',
            field=models.IntegerField(default=101),
        ),
    ]
