# Generated by Django 3.2 on 2021-07-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analiz', '0022_alter_acos_acos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acos',
            name='acos',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
