# Generated by Django 3.2 on 2021-07-21 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analiz', '0023_alter_acos_acos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ACOS',
        ),
    ]
